### ISSUE TITLE
Potential API Changes

### ISSUE THREAD

**Issue by wardlem** [JBaczuk/bscript-parser#19]
It would make sense to me to export the following functions:

```
// main functions
parseAsm(asm :: string) => Script
parseRaw(script :: Buffer|string, encoding='hex') => Script

// convenience functions
asmToScript(asm :: string, outputEncoding='binary') => Buffer|string
scriptToAsm(script :: Buffer|string, encoding='hex') => string
normalizeAsm(asm :: string) => string
```

The parseAsm would return a `Script` object with the following def:

```
class Script {
  constructor(tokens) {
    this.tokens = tokens
  }

  toAsm() {
    // .. convert to assembly
  }

  toRaw() {
    // .. convert to raw script
  }

  toAddress(network=BITCOIN_MAINNET) {
    // .. returns an address if the script is recognized as a standard address script
  }

  get redeemScript() {
    // .. returns the redeem script if the scriptType is 'p2wsh' or 'p2sh' as a Script object
    // .. returns undefined (?) if the scriptType does not have a redeem
  }

  get scriptType() {
    // .. returns a string (i.e. 'p2sh') if the script is recognized as a standard script type
    // .. returns undefined (?) if the script does not match a standard script
  }
}
```

The primary motivation for this would be to gain access to the parsed tokens.  The tokens could then be converted into a 'binary' by an upstream project and executed.  The tokens could also be utilized by an upstream code editor for bscript.

However, this would be a breaking change and may require a bump to new major version.

**UPDATED**: To address #6 and #7.

**Comment by JBaczuk** [comment]
Yeah I like this idea, but there hasn't been a release, so it's more of a redo of `v1.0` IMO. Maybe the `toRaw` could be more explicit about the format it exports, or split it into multiple methods like:

1. `toRawHex`
2. `toBuffer`

**Comment by wardlem** [comment]
> Maybe the toRaw could be more explicit about the format it exports

Yeah.  That makes sense.  The alternative would be to add an `encoding` parameter to the `toRaw` method, but I think I like breaking it into separate methods like you described is better.

**Comment by wardlem** [comment]
#22, #23 and #24 were created based on this issue.

**Comment by wardlem** [comment]
Closing this since it was agreed upon and additional issues have been created from it.
