### ISSUE TITLE
Convert script to and from an address

### ISSUE THREAD

**Issue by wardlem** [JBaczuk/bscript-parser#35]
Requires two new methods and one new (getter) property:

- `BScript.fromAddress(address, options = {})`
- `BScript#toAddress(options = {})`
- `get BScript#isAddress`

Options and defaults should be:

- **bech32**: `'bc'`
- **pubKeyHash**: `0x00`
- **scriptHash**: `0x05`

Optional convenience methods:

- `asmToAddress`
- `addressToAsm`
- `rawToAddress`
- `addressToRaw`

**Comment by wardlem** [comment]
I expect that these methods will throw if the script does not match an address.

Is `isAddress`, `hasAddress`, or something else the most correct for indicating whether or not a script can be converted to a standard address?

**Comment by wardlem** [comment]
Added the convenience methods as a separate issue: #37.

**Comment by JBaczuk** [comment]
> Is isAddress, hasAddress, or something else the most correct for indicating whether or not a script can be converted to a standard address?

Hmm, probably `hasAddress` or maybe `isAddressable` or `canCreateAddress`.
