### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by wardlem** [JBaczuk/bscript-parser#39]
Needs proper API documentation.  This might be included as a section of the `README.md` file.

Things to document: 

- [x] BScript class 
  - [x] Constructor
  - [x] Instance Properties
    - [x] `tokens`
    - [x] `hasAddress`
    - [x] `scriptType`
    - [x] `redeemScript`
  - [x] Instance Methods
    - [x] `toRaw`
    - [x] `toAsm`
    - [x] `toAddress`
  - [x] Static Methods
    - [x] `fromRaw`
    - [x] `fromAsm`
    - [x] `fromAddress`
- [x] Token class
  - [x] Constructor
  - [x] Instance Properties
    - [x] `type`
    - [x] `value`
    - [x] `startIndex`
    - [x] `endIndex`
  - [x] Instance Methods
    - [x] `toScript`
    - [x] `toAsm`
    - [x] `toString` (alias for `toAsm`)
  - [x] Static Properties
    - [x] Token Types: `LITERAL`, `OPCODE`, `PLACEHOLDER`
  - [x] Static Methods
    - [x] Constructor Helpers: `literal`, `opcode`, `placeholder`
- [x] Convenience Methods
  - [x] `rawToAsm`
  - [x] `rawToAddress`
  - [x] `asmToRaw`
  - [x] `asmToAddress`
  - [x] `addressToRaw`
  - [x] `addressToAsm`
- [x] Opcode Helpers
  - [x] `opcodeForWord`
  - [x] `wordForOpcode`
  - [x] `opcodeIsValid`
  - [x] `wordIsValid`
  - [x] `descriptionForOpcode`
  - [x] `descriptionForWord`
  - [x] `inputDescriptionForOpcode`
  - [x] `inputDescriptionForWord`
  - [x] `outputDescriptionForOpcode`
  - [x] `outputDescriptionForWord`
  - [x] `opcodeIsDisabled`
  - [x] `wordIsDisabled`
- [x] Options Struct
  - [x] `encoding` (for raw script buffer conversion)
  - [x] `literalStyle` (for asm stringification)
  - [x] `opcodeStyle` (for asm stringification)
  - [x] `terms` (object of overrides & additions for term opcodes)
  - [x] `opcodes (object of overrides for opcode terms, inverse of terms)`
  - [x] `pubKeyHash`
  - [x] `scriptHash`
  - [x] `bech32` (the prefix, i.e. `'bc'`)
  - [x] `allowPlaceHolders` (for asm parser)

**Comment by JBaczuk** [comment]
I think this would be good in the README too.
