### ISSUE TITLE
Export the Token class

### ISSUE THREAD

**Issue by wardlem** [JBaczuk/bscript-parser#40]

**Comment by JBaczuk** [comment]
Can you explain?

**Comment by wardlem** [comment]
> Can you explain

I would like to add the Token class as a top-level export of the module:

```javascript
// in module index.js
BScript.Token = require('src/token')

// in somefile.js somewhere
const {Token} = require('bscript-parser')
```

**Comment by wardlem** [comment]
The motivation for this is that token objects have properties that could be useful for doing things such as syntax highlighting (the start and end of the location token in the source text/buffer).
