### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/bscript-parser#45]
A command line interface would be awesome. If you could install the module globally and execute commands like

```
$ bsp rawtoasm a914c9f05571026bc94ad04ae03bf108d4bbe6815f1387
OP_HASH160 c9f05571026bc94ad04ae03bf108d4bbe6815f13 OP_EQUAL
```

**Comment by wardlem** [comment]
@JBaczuk Is this something you want post-`v1.1.0` for that release?  Also, is this something you want to tackle, or should I?

**Comment by JBaczuk** [comment]
Maybe we should add it to the `v1.1.0` release. I'm thinking it might be a good task for me to tackle, so I can better understand how the module works.
