### ISSUE TITLE
opcode hex output

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/bscript-parser#51]
It would be nice to get hex output from `opcodeForWord` as an option and to be able to pass hex into `wordForOpcode`

**Comment by wardlem** [comment]
Is it not just as convenient to do: `opcodeForWord('OP_DUPE').toString(16)` and `wordForOpcode(parseInt('0xaa'))`?

**Comment by JBaczuk** [comment]
I think you're right about the `opcodeForWord` that is convenient. But, say you have a variable with a hex string it would be convenient to do:

```
let op = '0xaa';
word = wordForOpcode(op);
```

**Comment by wardlem** [comment]
Makes sense.  Let's do it.
