### ISSUE TITLE
Special handling of 0x01-0x4b in descriptionForOpcode function

### ISSUE THREAD

**Issue by wardlem** [JBaczuk/bscript-parser#56]
Currently, each of these opcodes returns the string `'The next opcode bytes is data to be pushed onto the stack'`, but should instead replace the word `opcode` with the actual number of bytes that will be pushed onto the stack.  For example, `descriptionForOpcode(0x02)` should return `'The next 2 bytes is data to be pushed onto the stack'`.

**Comment by wardlem** [comment]
@JBaczuk I would like your opinion on whether or not this should be implemented.

**Comment by JBaczuk** [comment]
> @JBaczuk I would like your opinion on whether or not this should be implemented.

Yeah I think that is the right approach

**Comment by wardlem** [comment]
Sounds good, I will remove the needs discussion label then.
