### ISSUE TITLE
Show parsed redeem script

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/bscript-parser#7]
When a P2SH or P2WSH transaction is detected, parse and show the redeem script. This might require returning the parsed data as an object. Example:

```
parsedScript = {
    "script": "PUSHDATA(22)[0014d3530760601a3af53c7c93b01dfaf08d1ab156e0]",
    "redeem_script": "WITNESS_V0 PUSHDATA(20)[d3530760601a3af53c7c93b01dfaf08d1ab156e0]"
}
```

**Comment by wardlem** [comment]
Can this be a separate function?

**Comment by JBaczuk** [comment]
> Can this be a separate function?
I don't see why not.
